'use strict';

const COMMANDS = [
  {
    id: 'open.dashboard',
    title: 'Ouvrir le dashboard',
    description: 'Naviguer vers le tableau de bord principal.',
    category: 'navigation',
    target: '/dashboard',
    actions: ['open'],
    tags: ['dashboard', 'accueil'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.plugins',
    title: 'Ouvrir les plugins',
    description: 'Naviguer vers le gestionnaire de plugins locaux.',
    category: 'navigation',
    target: '/plugins',
    actions: ['open'],
    tags: ['plugins', 'extensions'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.workflows',
    title: 'Ouvrir les workflows',
    description: 'Naviguer vers les workflows IA visuels.',
    category: 'navigation',
    target: '/ai',
    actions: ['open'],
    tags: ['workflows', 'ia', 'automatisation'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.agents',
    title: 'Ouvrir les agents IA',
    description: 'Naviguer vers l\'orchestrateur d\'agents IA locaux.',
    category: 'navigation',
    target: '/ai',
    actions: ['open'],
    tags: ['agents', 'ia'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.memory',
    title: 'Ouvrir la memoire IA',
    description: 'Naviguer vers la memoire persistante IA locale.',
    category: 'navigation',
    target: '/ai',
    actions: ['open'],
    tags: ['memoire', 'ia', 'contexte'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.knowledge',
    title: 'Ouvrir la base de connaissances',
    description: 'Naviguer vers la base de connaissances locale.',
    category: 'navigation',
    target: '/ai',
    actions: ['open'],
    tags: ['knowledge', 'connaissances', 'ia'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.rag',
    title: 'Ouvrir le RAG local',
    description: 'Naviguer vers la recherche sur documentation locale.',
    category: 'navigation',
    target: '/ai',
    actions: ['open'],
    tags: ['rag', 'documentation', 'ia'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.diagnostics',
    title: 'Ouvrir les diagnostics',
    description: 'Naviguer vers le tableau de bord de diagnostics.',
    category: 'navigation',
    target: '/dashboard',
    actions: ['open'],
    tags: ['diagnostics', 'sante', 'systeme'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.backups',
    title: 'Ouvrir les sauvegardes',
    description: 'Naviguer vers le tableau de bord de sauvegardes.',
    category: 'navigation',
    target: '/sauvegardes',
    actions: ['open'],
    tags: ['sauvegardes', 'backup', 'restauration'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.updates',
    title: 'Ouvrir les mises a jour',
    description: 'Naviguer vers le gestionnaire de mises a jour.',
    category: 'navigation',
    target: '/dashboard',
    actions: ['open'],
    tags: ['mises-a-jour', 'update'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'run.diagnostics.dry',
    title: 'Lancer diagnostics (dry-run)',
    description: 'Executer une analyse diagnostics locale sans modification.',
    category: 'action',
    target: '/api/ai/agents/diagnostic-agent/run',
    actions: ['run-dry'],
    tags: ['diagnostics', 'dry-run', 'ia'],
    safe: true,
    dryRunRequired: true,
  },
  {
    id: 'run.workflow.dry',
    title: 'Lancer un workflow (dry-run)',
    description: 'Executer un workflow IA en mode simulation.',
    category: 'action',
    target: '/api/ai/workflows',
    actions: ['run-dry'],
    tags: ['workflow', 'dry-run', 'ia'],
    safe: true,
    dryRunRequired: true,
  },
  {
    id: 'search.knowledge',
    title: 'Rechercher dans la base de connaissances',
    description: 'Lancer une recherche dans la KB locale.',
    category: 'search',
    target: '/api/ai/knowledge/search',
    actions: ['search.knowledge'],
    tags: ['knowledge', 'recherche'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'search.memory',
    title: 'Rechercher dans la memoire IA',
    description: 'Lancer une recherche dans la memoire persistante locale.',
    category: 'search',
    target: '/api/ai/memory/search',
    actions: ['search.memory'],
    tags: ['memoire', 'recherche'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'copy.command',
    title: 'Copier une commande',
    description: 'Copier une commande dans le presse-papiers local.',
    category: 'utility',
    target: null,
    actions: ['copy'],
    tags: ['copier', 'presse-papiers'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'open.workspaces',
    title: 'Ouvrir les workspaces',
    description: 'Naviguer vers le gestionnaire de profils et workspaces locaux.',
    category: 'navigation',
    target: '/workspaces',
    actions: ['open'],
    tags: ['workspaces', 'profils', 'espaces'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'workspace.switch',
    title: 'Changer de workspace',
    description: 'Ouvrir le gestionnaire pour basculer vers un workspace local.',
    category: 'action',
    target: '/workspaces',
    actions: ['workspace.switch'],
    tags: ['workspace', 'switch', 'profil'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'workspace.export',
    title: 'Exporter un workspace',
    description: 'Ouvrir le gestionnaire pour exporter un workspace local.',
    category: 'action',
    target: '/workspaces',
    actions: ['workspace.export'],
    tags: ['workspace', 'export', 'sauvegarde'],
    safe: true,
    dryRunRequired: false,
  },
  {
    id: 'workspace.create',
    title: 'Creer un workspace',
    description: 'Ouvrir le gestionnaire pour creer un profil workspace local.',
    category: 'action',
    target: '/workspaces',
    actions: ['workspace.create'],
    tags: ['workspace', 'creer', 'nouveau'],
    safe: true,
    dryRunRequired: false,
  },
];

function getAllCommands() {
  return COMMANDS;
}

function getCommand(id) {
  return COMMANDS.find(c => c.id === id) || null;
}

function searchCommands(query) {
  if (!query) return COMMANDS;
  const lower = query.toLowerCase();
  return COMMANDS.filter(c =>
    c.title.toLowerCase().includes(lower) ||
    c.description.toLowerCase().includes(lower) ||
    c.tags.some(t => t.includes(lower))
  );
}

module.exports = { getAllCommands, getCommand, searchCommands };
